services:
  backend:
    build: ./backend
    container_name: backend_c1
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/rentalService
    command: nodemon server.js
  frontend:
    build: ./frontend3
    container_name: frontend_c1
    ports:
     - "5173:5173"
    volumes:
      - ./frontend3:/app
      - /app/node_modules
    depends_on:
      - backend
  mongo:
    image: mvertes/alpine-mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
